production:
  sessions:
    default:
      database: vivo_lottery_development
      hosts:
        - localhost:27017
      options:
  options:
development:
  sessions:
    default:
      database: vivo_lottery_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: vivo_lottery_development
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
